<?php

return array(
	'id'          => 'team-member',
	'types'       => array('team'),
	'title'       => __('Team Member Settings', 'luxe_framework'),
	'priority'    => 'high',
	'template'    => array(
		array(
			'type' => 'textbox',
			'name' => 'member-title',
			'label' => __('Team Member Title', 'luxe_framework'),
			'description' => __('Title or position of your team member.', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'soundcloud-rounded',
			'label' => __('Soundcloud Rounded', 'luxe_framework'),
			'description' => __('Soundcloud Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'pinterest-rounded',
			'label' => __('Pinterest Rounded', 'luxe_framework'),
			'description' => __('Pinterest Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'windows-rounded',
			'label' => __('Windows Rounded', 'luxe_framework'),
			'description' => __('Windows Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'addthis-rounded',
			'label' => __('Addthis Rounded', 'luxe_framework'),
			'description' => __('Addthis Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'sharethis-rounded',
			'label' => __('Sharethis Rounded', 'luxe_framework'),
			'description' => __('Sharethis Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'picasa-rounded',
			'label' => __('Picasa Rounded', 'luxe_framework'),
			'description' => __('Picasa Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'lastfm-rounded',
			'label' => __('Lastfm Rounded', 'luxe_framework'),
			'description' => __('Lastfm Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'technorati-rounded',
			'label' => __('Technorati Rounded', 'luxe_framework'),
			'description' => __('Technorati Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'mac-rounded',
			'label' => __('Mac Rounded', 'luxe_framework'),
			'description' => __('Mac Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'dribble-rounded',
			'label' => __('Dribble Rounded', 'luxe_framework'),
			'description' => __('Dribble Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'behance-rounded',
			'label' => __('Behance Rounded', 'luxe_framework'),
			'description' => __('Behance Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'facebook-rounded',
			'label' => __('Facebook Rounded', 'luxe_framework'),
			'description' => __('Facebook Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'google-rounded',
			'label' => __('Google Rounded', 'luxe_framework'),
			'description' => __('Google Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'skype-rounded',
			'label' => __('Skype Rounded', 'luxe_framework'),
			'description' => __('Skype Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'linkedin-rounded',
			'label' => __('Linkedin Rounded', 'luxe_framework'),
			'description' => __('Linkedin Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'deviantart-rounded',
			'label' => __('Deviantart Rounded', 'luxe_framework'),
			'description' => __('Deviantart Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'bing-rounded',
			'label' => __('Bing Rounded', 'luxe_framework'),
			'description' => __('Bing Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'twitter-rounded',
			'label' => __('Twitter Rounded', 'luxe_framework'),
			'description' => __('Twitter Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'myspace-rounded',
			'label' => __('Myspace Rounded', 'luxe_framework'),
			'description' => __('Myspace Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'flickr-rounded',
			'label' => __('Flickr Rounded', 'luxe_framework'),
			'description' => __('Flickr Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'tumblr-rounded',
			'label' => __('Tumblr Rounded', 'luxe_framework'),
			'description' => __('Tumblr Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'paypal-rounded',
			'label' => __('Paypal Rounded', 'luxe_framework'),
			'description' => __('Paypal Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'rss-rounded',
			'label' => __('Rss Rounded', 'luxe_framework'),
			'description' => __('Rss Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'stumbleupon-rounded',
			'label' => __('Stumbleupon Rounded', 'luxe_framework'),
			'description' => __('Stumbleupon Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'blogger-rounded',
			'label' => __('Blogger Rounded', 'luxe_framework'),
			'description' => __('Blogger Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'vimeo-rounded',
			'label' => __('Vimeo Rounded', 'luxe_framework'),
			'description' => __('Vimeo Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'wordpress-rounded',
			'label' => __('Wordpress Rounded', 'luxe_framework'),
			'description' => __('Wordpress Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'youtube-rounded',
			'label' => __('Youtube Rounded', 'luxe_framework'),
			'description' => __('Youtube Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'yahoo-rounded',
			'label' => __('Yahoo Rounded', 'luxe_framework'),
			'description' => __('Yahoo Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'aim-rounded',
			'label' => __('Aim Rounded', 'luxe_framework'),
			'description' => __('Aim Rounded URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'dribble',
			'label' => __('Dribble', 'luxe_framework'),
			'description' => __('Dribble URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'behance',
			'label' => __('Behance', 'luxe_framework'),
			'description' => __('Behance URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'facebook',
			'label' => __('Facebook', 'luxe_framework'),
			'description' => __('Facebook URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'google',
			'label' => __('Google', 'luxe_framework'),
			'description' => __('Google URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'skype',
			'label' => __('Skype', 'luxe_framework'),
			'description' => __('Skype URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'linkedin',
			'label' => __('Linkedin', 'luxe_framework'),
			'description' => __('Linkedin URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'deviantart',
			'label' => __('Deviantart', 'luxe_framework'),
			'description' => __('Deviantart URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'bing',
			'label' => __('Bing', 'luxe_framework'),
			'description' => __('Bing URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'twitter',
			'label' => __('Twitter', 'luxe_framework'),
			'description' => __('Twitter URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'myspace',
			'label' => __('Myspace', 'luxe_framework'),
			'description' => __('Myspace URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'flickr',
			'label' => __('Flickr', 'luxe_framework'),
			'description' => __('Flickr URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'tumblr',
			'label' => __('Tumblr', 'luxe_framework'),
			'description' => __('Tumblr URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'paypal',
			'label' => __('Paypal', 'luxe_framework'),
			'description' => __('Paypal URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'rss',
			'label' => __('Rss', 'luxe_framework'),
			'description' => __('Rss URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'stumbleupon',
			'label' => __('Stumbleupon', 'luxe_framework'),
			'description' => __('Stumbleupon URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'blogger',
			'label' => __('Blogger', 'luxe_framework'),
			'description' => __('Blogger URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'vimeo',
			'label' => __('Vimeo', 'luxe_framework'),
			'description' => __('Vimeo URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'wordpress',
			'label' => __('Wordpress', 'luxe_framework'),
			'description' => __('Wordpress URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'youtube',
			'label' => __('Youtube', 'luxe_framework'),
			'description' => __('Youtube URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'yahoo',
			'label' => __('Yahoo', 'luxe_framework'),
			'description' => __('Yahoo URL', 'luxe_framework'),
		),
        array(
			'type' => 'textbox',
			'name' => 'aim',
			'label' => __('Aim', 'luxe_framework'),
			'description' => __('Aim URL', 'luxe_framework'),
		),
		
	),
);

/**
 * EOF
 */